//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Nullable<int> IDRegion { get; set; }
        public Nullable<int> IDUniversity { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int House { get; set; }
        public string Phone { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual University University { get; set; }
    }
}
