//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialty
    {
        public int ID { get; set; }
        public Nullable<int> IDUniversity { get; set; }
        public string NameOfSpecialty { get; set; }
        public Nullable<int> Сontest { get; set; }
        public Nullable<int> PaymentAmount { get; set; }
    
        public virtual University University { get; set; }
    }
}
